// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmclient from "../wasmclient"

const russfestHandlers = new Map<string, (evt: RussfestEvents, msg: string[]) => void>([
	["russfest.test", (evt: RussfestEvents, msg: string[]) => evt.test(new EventTest(msg))],
]);

export class RussfestEvents implements wasmclient.IEventHandler {
	test: (evt: EventTest) => void = () => {};

	public callHandler(topic: string, params: string[]): void {
		const handler = russfestHandlers.get(topic);
		if (handler) {
			handler(this, params);
		}
	}

	public onRussfestTest(handler: (evt: EventTest) => void): void {
		this.test = handler;
	}
}

export class EventTest extends wasmclient.Event {
	
	public constructor(msg: string[]) {
		super(msg);
	}
}
